xenanetworks/open-automation-python-api

- .github/ISSUE_TEMPLATE/config.yml
> added issue template

- xoa_driver/internals/core/commands/m_commands.py
- xoa_driver/internals/core/commands/p_commands.py
- xoa_driver/internals/core/commands/pc_commands.py
- xoa_driver/internals/core/commands/pe_commands.py
- xoa_driver/internals/core/commands/pec_commands.py
- xoa_driver/internals/core/commands/pef_commands.py
- xoa_driver/internals/core/commands/pp_commands.py
- xoa_driver/internals/core/commands/pr_commands.py
- xoa_driver/internals/core/commands/ps_commands.py
This pull request is to fix some documentation mistakes. No driver source code is changed.
> Fix documentation

- xoa_driver/__init__.py
- xoa_driver/internals/core/protocol/struct_response.py
The bug in the parser causes P_MUTLICAST and P_MULTICASTEXT to fail.
Reference Issue Numbers: #55, [CAS-14487-Z7K9C7]
> fix(parser): Fix parsing bug

- xoa_driver/internals/core/commands/enums.py
- xoa_driver/internals/core/commands/pl1_commands.py
Signed-off-by: Michael Lilja <mli@xenanetworks.com>
> Support for PL1_LINKTRAIN_CMD and updated linkstatus counters

- LICENSE
- docs/source/api_ref/hlapiv1/_autosummary/ports/classes/xoa_driver.internals.hli_v1.ports.port_l23.family_g.PLoki100G3S1P.rst
- docs/source/api_ref/hlapiv1/_autosummary/ports/classes/xoa_driver.internals.hli_v1.ports.port_l23.family_g.PLoki100G3S1PSE.rst
- docs/source/api_ref/hlapiv1/_autosummary/ports/classes/xoa_driver.internals.hli_v1.ports.port_l23.family_g.PLoki100G3S1P_b.rst
- docs/source/api_ref/hlapiv1/_autosummary/ports/classes/xoa_driver.internals.hli_v1.ports.port_l23.family_h.PLoki100G5S1P.rst
- docs/source/api_ref/hlapiv1/_autosummary/ports/classes/xoa_driver.internals.hli_v1.ports.port_l23.family_h.POdin100G3S1P.rst
- docs/source/api_ref/hlapiv1/_autosummary/ports/classes/xoa_driver.internals.hli_v1.ports.port_l23.family_i.PLoki100G5S2P.rst
- docs/source/api_ref/hlapiv1/_autosummary/ports/classes/xoa_driver.internals.hli_v1.ports.port_l23.family_j.PThor100G5S4P.rst
- docs/source/api_ref/hlapiv1/_autosummary/ports/classes/xoa_driver.internals.hli_v1.ports.port_l23.family_k.PThor400G7S1P.rst
- docs/source/api_ref/hlapiv1/_autosummary/ports/classes/xoa_driver.internals.hli_v1.ports.port_l23.family_l.PThor400G7S1P_b.rst
- docs/source/api_ref/hlapiv1/_autosummary/ports/classes/xoa_driver.internals.hli_v1.ports.port_l23.family_l.PThor400G7S1P_c.rst
- docs/source/api_ref/hlapiv1/_autosummary/ports/classes/xoa_driver.internals.hli_v1.ports.port_l23.family_l.PThor400G7S1P_d.rst
- docs/source/api_ref/llapi/l23/pc_commands.rst
- docs/source/conf.py
- xoa_driver/__init__.py
- xoa_driver/internals/core/commands/m_commands.py
- xoa_driver/internals/core/commands/pc_commands.py
- xoa_driver/internals/core/commands/pf_commands.py
- xoa_driver/internals/core/commands/ps_commands.py
- xoa_driver/internals/hli_v1/ports/port_l23/family_g.py
- xoa_driver/internals/hli_v1/ports/port_l23/family_h.py
- xoa_driver/internals/hli_v1/ports/port_l23/family_i.py
- xoa_driver/internals/hli_v1/ports/port_l23/family_j.py
- xoa_driver/internals/hli_v1/ports/port_l23/family_k.py
- xoa_driver/internals/hli_v1/ports/port_l23/family_l.py
- xoa_driver/internals/hli_v1/ports/port_l23/family_l1.py
- Add missing PcsPma and SerDes attributes for some high-speed ports
- Fix the bug that fails documentation generation
- Remove typehints from documentation
- Update copyright date
- Fix cross-reference issue in PC_ LL-API
- Partially update docstrings in M_ LL-API
> Improve documentation cross-reference issue

- LICENSE
- xoa_driver/__init__.py
- xoa_driver/internals/ports/port_l23/pcs_pma_ghijkl.py
> fix(pcs_pma): Add PRBSConfig to PcsPma object

- xoa_driver/functions/anlt_ll_debug.py
- xoa_driver/internals/core/commands/enums.py
- xoa_driver/internals/core/commands/pl1_commands.py
AN/LT needs to have a register level based debugging interface. The class introduced, will get the base addresses from Xenaserver and utilize them to create high-level abstractions in XOA.
Signed-off-by: Michael Lilja <mli@xenanetworks.com>
> Added support for anlt_ll_debug

- xoa_driver/functions/anlt.py
- xoa_driver/functions/anlt_ll_debug.py
- xoa_driver/functions/mgmt.py
- xoa_driver/functions/tools.py
> fix: GenericL23Port

- .github/workflows/execute-test-suite.yml
Also skip some path no need to testing.
> fix: Invoke testing only on push event

- xoa_driver/functions/anlt.py
- xoa_driver/functions/anlt_ll_debug.py
- xoa_driver/functions/tools.py
Rename lt_rx_analyzer to xla.
Added more low-level debug function
> Low-level debug rename and new functions

- xoa_driver/internals/core/commands/enums.py
Added - Log control, Strict mode, XLA mode enum values
> Updated enum

- docs/source/api_ref/hlfunc/anlt/index.rst
- xoa_driver/__init__.py
- xoa_driver/functions/anlt.py
> feat: TX tap autotune in hlfuncs

- xoa_driver/internals/hli_v1/ports/port_l23/chimera/filter_definition/general.py
- xoa_driver/internals/hli_v2/ports/port_l23/chimera/filter_definition/general.py
https://docs.xenanetworks.com/projects/xoa-cli/en/latest/cli_ref/impairment/pef_commands.html#pef-protocol
https://docs.xenanetworks.com/projects/xoa-cli/en/latest/cli_ref/impairment/pef_commands.html#pef-value
0 means return all segment values so need to change protocol_segment_index starts from 1.
> HLI of PEF_VALUE's protocol_segment_index starts from 1

- xoa_driver/internals/core/commands/pef_commands.py
We have discuss that "use" field on slack two month ago but forgot to commit delete it, here is it.
> Delete not exists field from PEF_TPLDSETTINGS

- xoa_driver/internals/commands/pef_commands.py
- xoa_driver/internals/hli_v2/ports/port_l23/chimera/pe_distribution.py
- xoa_driver/internals/hli_v2/ports/port_l23/chimera/port_emulation.py
Fix of https://github.com/xenanetworks/open-automation-python-api/issues/149 and cherry-pick some commits from v1 branch.
> Fix incorrect PEF command indices

- xoa_driver/internals/core/commands/pef_commands.py
pef_anyconfig the Hex sizes suppose to be 6 but in our code was set to 8
> fix wrang defenition pef_anyconfig

- xoa_driver/internals/hli_v1/ports/port_l23/chimera/filter_definition/shadow.py
- xoa_driver/internals/hli_v1/ports/port_l23/chimera/pe_custom_distribution.py
- xoa_driver/internals/hli_v2/ports/port_l23/chimera/filter_definition/shadow.py
- xoa_driver/internals/hli_v2/ports/port_l23/chimera/pe_custom_distribution.py
- xoa_driver/internals/hli_v2/ports/port_l23/chimera/port_emulation.py
- fix access incorrect property name of custom distribution 
- add HLI of PEF_CANCEL
- fix pass incorrect impairment index into PED_ENABLE
> Improve chimera related api

- .github/workflows/testing_auto.yml
- .github/workflows/testing_manual.yml
The same as: https://github.com/xenanetworks/open-automation-python-api/pull/156
It need to merge into main for invoke manual testing on webui.
> Add manual testing actions

- xoa_driver/internals/hli_v2/ports/port_l23/chimera/pe_custom_distribution.py
We could discuss this PR on next meeting.
```
cd = await self.hli_custom_distributions.add(
cust_id=cust_id,
linear=linear,
entry_count=entry_count,
data_x=data_x,
comment=comment,
)
```
> Make custom distributions as dictionary

- xoa_driver/internals/hli_v2/ports/port_l23/chimera/filter_definition/general.py
It needs to passing `filter_type` for prevent_set.
> Fix TPLD_ID filter setting of chimera

- xoa_driver/__init__.py
- xoa_driver/internals/commands/enums.py
NRZ = 0
PAM4 = 1
PAM4_WITH_PRECODINg = 2
> Fix LinkTrainEncoding enum

- xoa_driver/__init__.py
- xoa_driver/internals/hli_v1/modules/modules_l23/family_f.py
- xoa_driver/internals/hli_v1/modules/modules_l23/family_g.py
- xoa_driver/internals/hli_v1/ports/port_l23/family_f.py
- xoa_driver/internals/hli_v1/ports/port_l23/family_g.py
- xoa_driver/internals/hli_v2/modules/modules_l23/family_f.py
- xoa_driver/internals/hli_v2/modules/modules_l23/family_g.py
- xoa_driver/internals/hli_v2/ports/port_l23/family_f.py
- xoa_driver/internals/hli_v2/ports/port_l23/family_g.py
- xoa_driver/modules.py
- xoa_driver/ports.py
- xoa_driver/v2/modules.py
- xoa_driver/v2/ports.py
Odin-10G-6S-6P[a] and Loki-100G-3S-1P-B[b]
> Add support for two new modules

- xoa_driver/functions/cli.py
- xoa_driver/internals/commands/ps_commands.py
It contains fixes regarding Task https://app.asana.com/0/1199579174425509/1203173216342294/f
> Fix for pp_linkflap_param and ps_options commands
